# Setup
title:               Chad Hudson
tagline:             CISO
description:         Just another CISO
url:                 http://chadchudson.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Chad Hudson
  url:               https://chadchudson.com
  email:             chadchudson@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
